### ISSUE TITLE
Alert Module unable to find alertConfig.json

### ISSUE THREAD

**Issue by ehharvey** [kstencell/CSCN72030-Sec1-Group1#12]
It looks like the app is looking in the build folder to find my existing config file.

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'CrewDragonHMI.AlertModule' threw an exception.
  Source=CrewDragonHMI
  StackTrace:
   at CrewDragonHMI.AlertModule.ReceiveSensorValue(String module_name, Int32 value) in C:\Users\emilh\git\CSCN72030-Sec1-Group1\CrewDragonHMI\AlertModule.cs:line 104
   at CrewDragonHMI.MainWindow.Alert_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\emilh\git\CSCN72030-Sec1-Group1\CrewDragonHMI\MainWindow.xaml.cs:line 158
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

  This exception was originally thrown at this call stack:
    [External Code]
    CrewDragonHMI.AlertModule.AlertModule() in AlertModule.cs

Inner Exception 1:
FileNotFoundException: Could not find file 'C:\Users\emilh\git\CSCN72030-Sec1-Group1\CrewDragonHMI\bin\Debug\net5.0-windows\alertConfig.json'.

```

**Comment by ehharvey** [comment]
Exploring copying the file over using post-build events in visual studio.

**Comment by ehharvey** [comment]
This config in the project properties fixed the issue. Closing.
![image](https://user-images.githubusercontent.com/36806437/143502886-d1f862e5-1583-46a6-b86a-62af7cf81816.png)
